### ISSUE TITLE
AttributeError: 'DatasetReader' object has no attribute 'read_band'

### ISSUE THREAD

**Issue by PierreRCM** [mdbartos/pysheds#88]
Hi,

I could not find the read_band method  which is from rasterio? 
This error appears in read_raster
Maybe a problem of version ?
`            if window is None:
                shape = f.shape
                if len(f.indexes) > 1:
                    data = np.ma.filled(f.read_band(band))
                else:
                    data = np.ma.filled(f.read())
                affine = f.transform
                data = data.reshape(shape)`

Any ideas ? :D

**Comment by PierreRCM** [comment]
Thanks for the answer,

I can't find 1.0.4 in all version proposed

There are : 

1.0.22
1.0.21
1.0.13
0.36.0
0.25.0
0.24.0

which one would match with pysheds ?

Thanks

**Comment by mdbartos** [comment]
I think it should work with one of the 1.0.x versions.

**Comment by mdbartos** [comment]
What version do you currently have?

**Comment by PierreRCM** [comment]
The last one 1.0.22

**Comment by mdbartos** [comment]
Ah, I just looked at the rasterio docs. It looks like `read_band` was replaced with `read` in v1.0. I guess I just never had any test cases with multiple bands.

The line:

```python
data = np.ma.filled(f.read_band(band))
```

Would need to be changed to:

```python
data = np.ma.filled(f.read(band))
```

**Comment by PierreRCM** [comment]
Oh nice ! At least i didn't bother you for no reason :D

Thanks

**Comment by mdbartos** [comment]
Please reopen if this issue persists.

**Comment by mdbartos** [comment]
Thanks for letting me know. I didn't realize this was never fixed. Unit tests never raised this error because only single-band rasters were used. I will fix as soon as possible.
